### ISSUE TITLE
FAGDec failure with code 80010002

### ISSUE THREAD

**Issue by mchubby** [CelesteBlue-dev/PSVita-RE-tools#11]
Hello,

Running FAGDec with Enso 3.65, I run into this issue with some games
```
Starting dump...
Starting kuEntente plugin: 8002d013
Starting userAllied plugin: 40060067
ERROR kuEntente is busy
Obtaining AID: 0
Obtaining Fixed Rif name: 6488b73b912a753a492e2714e9b38bc7.rif
Unmounting PFS: 80800002
Switching to: PCSG01182
Mounting PFS: 0
Using rif: ux0:license/app/PCSG01182/6488b73b912a753a492e2714e9b38bc7.rif
Decrypting: ux0:/app/PCSG01182/eboot.bin
Outpath: ux0:/FAGDec/app/PCSG01182/eboot.bin.elf
Waiting for decrypter
kuEntente: Getting klicense from rif
kuEntente: kuEntente Returned: 800f0b37
Could not properly save self auth: 80010002
Stripping NpDRM from header...
Got elf digest
Saving digest to: ux0:/FAGDec/app/PCSG01182/eboot.bin.elf.sha256
Module done
Unmounting PFS: 0
Done
```

(the line ending with 80010002 is highlighted in red)

It results in an invalid, 212-byte elf file. The common point I found is their being titles needing 3.67 or higher.

Is there any step I'm missing?

These games run normally thorugh repatch+comppack or ref00d, by the way.

**Comment by mchubby** [comment]
Apparently, it's [sceSblAuthMgrAuthHeaderForKernel](https://github.com/CelesteBlue-dev/PSVita-RE-tools/blob/b08bd903071ac0accee1c3590f74ce6a976967f6/FAGDec/src/kplugin/kentente.c#L90) that returns 0x800f0b37

**Comment by CelesteBlue-dev** [comment]
According to NPS:
```
PCSG01182	JP	Kanojo * Step (3.61+!) [3.67]
```
That means you can't decrypt this game on a FW <3.67.
You can bypass this by having ref00d.skprx running.

**Comment by CelesteBlue-dev** [comment]
Related to #14
