### ISSUE TITLE
FaGDec+reF00D

### ISSUE THREAD

**Issue by ghost** [CelesteBlue-dev/PSVita-RE-tools#14]
Is it possible to make FAGDec use the reF00D plugin with the keys.bin.?Then decryption is possible on any version of the console.

**Comment by BpyH64** [comment]
Created a utility analogue FAGDec only for PC Win64. The problem is solved.

**Comment by YuriSizuku** [comment]
You can use [0syscall6](https://github.com/SKGleba/0syscall6) to dump instead of reFooD. I have tesed to dump PCSG01282 (3.69) with 3.68 firmware.

**Comment by CelesteBlue-dev** [comment]
FAGDec being less used since that keys are public, I won't improve FAGDec and deprecate it if you have a PC, use sceutils for now or keep using current FAGDec.
