### ISSUE TITLE
vita-make-fself.exe change ELF file

### ISSUE THREAD

**Issue by ghost** [CelesteBlue-dev/PSVita-RE-tools#15]
When creating FSELF file
 vita-make-fself.exe 111.elf 222.bin 

ELF file itself changes inside file 222.bin. This can be proved if we compare WinHex the original 111.elf with the 222.bin at the address (0x1000:end file)

**Comment by CelesteBlue-dev** [comment]
vita-make-fself.exe is not part of this repository.
