### ISSUE TITLE
Create better open source makeSelf for PC

### ISSUE THREAD

**Issue by chaoskagami** [CelesteBlue-dev/PSVita-RE-tools#4]
Trying to port the stupid Utawarerumono resolution hack for my personal use. It's impossible in the current state.

Namely, the readme makes clear you need the SDK leak make_fself.exe, and this is not sane, advisable, and also won't work unless it's run under WINE for Linux people.

Aside from this, *cough*rot13*cough* Guvf frrzf gb erdhver gur 3.55 FQX yrnx, juvpu V pnaabg sbe gur yvsr bs zr svaq. Gur byqre LYbQ yrnx pna or sbhaq, ohg znxr_sfrys.rkr sebz gurer vf vafhssvpvrag naq chxrf jvgu 'REEBE: guvf svyr vf CEK2 sbezng, ohg cebtenz frtzrag vf CEK sbezng' naq qbrfa'g cebivqr gur -p bcgvba.

Long and short, is there any other method I can use such as building with vita-make-fself and copying stuff from the SCE ELF header from the original eboot.bin?

**Comment by CelesteBlue-dev** [comment]
have you tried using instead of make_fself.exe :
vita-make-fself.exe -c myelf.elf out.self
then following the normal steps ?

**Comment by dots-tb** [comment]
The padding is made incorrectly,  I do not know how to replicate the original padding of make_fself @chaoskagami , I guess we could make a version that takes the original sce_header and copies it to an ELF, if you'd like that.

**Comment by SilicaAndPina** [comment]
Just manually copy the header and update sha256

**Comment by TheRadziu** [comment]
@chaoskagami you can use make_fself linked in nonpdrm modding tutorial, works just fine with fagdec generated ELFs or unself'ed ELF:
https://github.com/TheRadziu/NoNpDRM-modding/wiki#eboot-modding-andor-running-365-games-on-360-and-365

**Comment by chaoskagami** [comment]
@TheRadziu The point here is that requiring a tool by Sony that's illegal to possess without a developer contract is unacceptable. There needs to be another solution that doesn't involve usage of make_fself.exe. Aside from this, requiring WINE for Linux people to use this tool is absurdity.

*cough*rot13 again*cough*V nyernql ybat fvapr svkrq gur ceboyrz ol svaqvat fbzr bofpher-nff zntarg naq fuerqqrq gur svyrf nsgrejneqf.

@CelesteBlue-dev According to the README, that doesn't work. Rather than waste my time testing, I assumed that the people here know what they're talking about.

@dots-tb That's probably the best way to go about it, I'd guess. As long as it doesn't require any illegal copyrighted content, I'm all for any solution here.

**Comment by TheRadziu** [comment]
As I said, this is a temporary solution until dots stop distracted on the other projects. Elf injector will be the way to go. Should be open sourced thus, should be also compilable and usable on linux or mac.

**Comment by dots-tb** [comment]
@chaoskagami https://github.com/CelesteBlue-dev/PSVita-RE-tools/tree/master/elf_injector
Please try it out. ;)
