### ISSUE TITLE
Compatability pack made using Fagdec.vpk

### ISSUE THREAD

**Issue by wolfbitez23** [CelesteBlue-dev/PSVita-RE-tools#5]
I made a compatability pack for Fate Extella: THE UMBRAL STAR (PCSE00928) version 1.01 using the fagdec.vpk, the issue is that the game doesn't start when its opened on a 3.60 Vita it is just stuck on the image.

Although making a compatability pack for 1.00 is all good and working.

Please kind of help me to fix this

**Comment by TheRadziu** [comment]
did you replace 1.00 comp pack with 1.01 comp pack files and overwrite them? 

sometimes updates do not have required files from basegame, hence its needed to overwrite basegame comp pack files with desired patch comp pack files.

**Comment by wolfbitez23** [comment]
that fixed it, 
Thanks for helping me will be submitting the compack on the compacks thread on the other git.

**Comment by TheRadziu** [comment]
@wolfbitez23 depends on what julio says about contributing since he and dots are working on automatic comp pack making & updating repo without human interaction, that would mean that everyday any missing 3.61+ basegame or patch comp packs will be made automatically

**Comment by wolfbitez23** [comment]
whoa thats cool, okay then since I can't seem to generate my public SSH Key from my windows to be able to pull on the git
