### ISSUE TITLE
Game gets stuck on splash screen

### ISSUE THREAD

**Issue by masterrite** [CelesteBlue-dev/PSVita-RE-tools#6]
YS VIII Asian version gets stuck on splash screen. I'm using h-encore 3.68 with PSV 2000

**Comment by CelesteBlue-dev** [comment]
Not related to StorageMgr.
Ask help on discord or IRC.

**Comment by masterrite** [comment]
I mean this is caused by ioplus.skprx. Sorry, I should've been clearer. I used ioplus 0.1 as detected by dot and ys viii gets stuck. Once I switch back to kuio.skprx the game works fine.
